FROM ubuntu:22.04

WORKDIR /app

EXPOSE 80
EXPOSE 443

RUN apt update && \
    apt install -y wget && \
    wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt update && \
    apt install -y dotnet-sdk-9.0 && \
    dotnet tool install -g dotnet-ef --version 9.0.1

WORKDIR /src

COPY ["Web/Web.csproj", "Web/"]
COPY ["Application/Application.csproj", "Application/"]
COPY ["Domain/Domain.csproj", "Domain/"]
COPY ["EmailSender/EmailSender.csproj", "EmailSender/"]
COPY ["Persistence/Persistence.csproj", "Persistence/"]

RUN dotnet restore "Web/Web.csproj"
RUN echo 

RUN dotnet ef database update --project /src/Persistence/Persistence.csproj

RUN mkdir /app

WORKDIR /src/Web
RUN dotnet publish "Web.csproj" -c Release -o /app/ /p:UseAppHost=false

WORKDIR /app
COPY ["publish/", "./"]

ENTRYPOINT ["dotnet", "Web.dll"]
